# COMMON APPLICATION PROPERTIES

# start services on random port by default
server.port: 0

# embedded database init, supports mysql too trough the 'mysql' spring profile
petclinic.database: mysqldb
spring:
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql
    url: jdbc:Mysql://localhost:3306/petclinic?useSSL=false
    username: Tom
    password: tom
    initialization-mode: never
#spring:
#  datasource:
 #   schema: classpath*:db/hsqldb/schema.sql
#    data: classpath*:db/hsqldb/data.sql
#  sleuth:
#    sampler:
#      percentage: 1.0

# JPA
spring.jpa.hibernate.ddl-auto: none

# Spring Boot 1.5 makes actuator secure by default
management.security.enabled: false
# Enable all Actuators and not only the two available by default /health and /info starting Spring Boot 2.0
management.endpoints.web.exposure.include: "*"

# Temporary hack required by the Spring Boot 2 / Spring Cloud Finchley branch
# Waiting issue https://github.com/spring-projects/spring-boot/issues/13042
spring.cloud.refresh.refreshable: false


# Logging
logging.level.org.springframework: INFO

#spring:
#  profiles: local
#  GIT_REPO: https://github.com/thetterscheidt/petclinic

---

#    initialization-mode: NEVER
